UTB.Eshop.Web/Areas/Admin/Controllers/CarouselController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UTB.Eshop.Domain.Abstraction;
using UTB.Eshop.Web.Models.Database;
using UTB.Eshop.Web.Models.Entities;
using UTB.Eshop.Web.Models.Identity;
using UTB.Eshop.Web.Models.ViewModels;

namespace UTB.Eshop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = nameof(Roles.Admin) + ", " + nameof(Roles.Manager))]
    public class CarouselController : Controller
    {
        readonly EshopDbContext eshopDb;
        IFileUpload fileUpload;
        ICheckFileContent checkFileContent;
        ICheckFileLength checkFileLength;
        public CarouselController(EshopDbContext eshopDbContext,
                                    IFileUpload fileUpload,
                                    ICheckFileContent checkFileContent,
                                    ICheckFileLength checkFileLength)
        {
            eshopDb = eshopDbContext;
            this.fileUpload = fileUpload;
            this.checkFileContent = checkFileContent;
            this.checkFileLength = checkFileLength;
        }

        public IActionResult Index()
        {
            List<CarouselSlide> carouselSlides = eshopDb.CarouselSlides.ToList();

            return View(carouselSlides);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarouselSlideFileRequired carouselSlide)
        {
            ModelState.Remove(nameof(CarouselSlide.ImageSrc));
            if (ModelState.IsValid)
            {
                if (checkFileLength.CheckFileLength(carouselSlide.Image, 5_000_000))
                {

                    fileUpload.ContentType = "image";
                    fileUpload.FileLength = 5_000_000;
                    carouselSlide.ImageSrc = await fileUpload.FileUploadAsync(carouselSlide.Image, Path.Combine("img", "carousel"));

                    ModelState.Clear();
                    bool validated = TryValidateModel(carouselSlide);
                    if (validated)
                    {
                        eshopDb.CarouselSlides.Add(carouselSlide);

                        eshopDb.SaveChanges();

                        return RedirectToAction(nameof(CarouselController.Index));
                    }

                }
            }

            return View(carouselSlide);
        }


        public IActionResult Edit(int ID)
        {
            CarouselSlide carSlide = eshopDb.CarouselSlides.FirstOrDefault(carouselItem => carouselItem.ID == ID);

            if (carSlide != null)
            {
                return View(carSlide);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CarouselSlide carouselSlide)
        {
            CarouselSlide carSlide = eshopDb.CarouselSlides.FirstOrDefault(carouselItem => carouselItem.ID == carouselSlide.ID);

            if (carSlide != null)
            {
                ModelState.Remove(nameof(CarouselSlide.ImageSrc));
                if (ModelState.IsValid)
                {
                    if (carouselSlide.Image != null)
                    {
                        if (checkFileLength.CheckFileLength(carouselSlide.Image, 5_000_000))
                        {

                            fileUpload.ContentType = "image";
                            fileUpload.FileLength = 5_000_000;
                            carouselSlide.ImageSrc = await fileUpload.FileUploadAsync(carouselSlide.Image, Path.Combine("img", "carousel"));

                            ModelState.Clear();
                            if (TryValidateModel(carouselSlide))
                            {
                                carSlide.ImageSrc = carouselSlide.ImageSrc;
                            }
                            else
                            {
                                return View(carouselSlide);
                            }
                        }
                        else
                        {
                            return View(carouselSlide);
                        }
                    }

                    carSlide.ImageAlt = carouselSlide.ImageAlt;

                    eshopDb.SaveChanges();

                    return RedirectToAction(nameof(CarouselController.Index));
                }
                else
                    return View(carouselSlide);
            }

            return NotFound();
        }


        public IActionResult Delete(int ID)
        {
            CarouselSlide carSlide = eshopDb.CarouselSlides.FirstOrDefault(carouselSlide => carouselSlide.ID == ID);

            if (carSlide != null)
            {
                eshopDb.CarouselSlides.Remove(carSlide);

                eshopDb.SaveChanges();

                return RedirectToAction(nameof(CarouselController.Index));
            }

            return NotFound();
        }
    }
}

UTB.Eshop.Web/Areas/Admin/Views/Carousel/Create.cshtml
@model CarouselSlideFileRequired
@{
    ViewData["Title"] = "Vytvoření nového Carouselu";
    ViewBag.Akce = "Create";
}
<h1>@ViewData["Title"]</h1>

<partial name="CreateEditForm" model="Model" />

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/FileContentValidation.js"></script>
    <script src="~/js/FileSizeValidation.js"></script>
}

UTB.Eshop.Web/Areas/Admin/Views/Carousel/CreateEditForm.cshtml
@model CarouselSlide

@{
    if (ViewBag.Akce != null)
    {
        <form asp-action="@ViewBag.Akce" method="post" enctype="multipart/form-data">
            @{
                if (ViewBag.Akce == "Edit")
                {
                    <input asp-for="ID" type="hidden" />
                }
            }
            <div asp-validation-summary="All"></div>
            <div class="form-group">
                <label asp-for="Image">Image</label>
                @{
                    if (ViewBag.Akce == "Edit")
                    {
                        <input asp-for="Image" class="form-control-file">
                    }
                    else
                    {
                        <input asp-for="Image" class="form-control-file" data-val-required="The Image field is required.">
                    }
                }
                <span asp-validation-for="Image"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageAlt">Image Alternative Text</label>
                <input asp-for="ImageAlt" class="form-control" placeholder="Enter alternative text ...">
                <span asp-validation-for="ImageAlt"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    }
}

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/FileContentValidation.js"></script>
    <script src="~/js/FileSizeValidation.js"></script>
}

UTB.Eshop.Web/Areas/Admin/Views/Carousel/Edit.cshtml
@model CarouselSlide
@{
    ViewData["Title"] = "Vytvoření nového Carouselu";
    ViewBag.Akce = "Edit";
}
<h1>@ViewData["Title"]</h1>

<partial name="CreateEditForm" model="Model" />

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/FileContentValidation.js"></script>
}

UTB.Eshop.Web/Areas/Admin/Views/Carousel/Index.cshtml
@model List<CarouselSlide>
@{
    ViewData["Title"] = "Carousel items";
}
<h1>@ViewData["Title"]</h1>

<a asp-area="Admin" asp-controller="Carousel" asp-action="Create">Create new Carousel</a>
@{
    if (Model != null && Model.Count > 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Image Source</th>
                    <th scope="col">Image Alternative Text</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var carouselSlide in Model)
                    {
                        <tr>
                            <th scope="row">@carouselSlide.ID</th>
                            <td>@carouselSlide.ImageSrc</td>
                            <td>@carouselSlide.ImageAlt</td>
                            <td><a asp-area="Admin" asp-controller="Carousel" asp-action="Edit" asp-route-ID="@carouselSlide.ID">Edit</a></td>
                            <td><a asp-area="Admin" asp-controller="Carousel" asp-action="Delete" asp-route-ID="@carouselSlide.ID" onclick="return ConfirmDelete();">Delete</a></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    }
}

@section Scripts
{
    <script src="~/js/dialogs.js"></script>
}